apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deportista
  labels: 
     app: deportista

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: deportista

  template:
    metadata:
      labels:
        app: deportista
    spec:
      containers:
      - name: deportista
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ENV1
        - name: AWS_SECRET_ACCESS_KEY
          value: ENV2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
