apiVersion: v1
kind: Service
metadata:
  name: deportista
  labels:
    app: deportista
spec:
  type: ClusterIP
  selector:
    app: deportista

  ports:
    - port: 80
      targetPort: 5004
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deportista-ingress
  
spec:
  ingressClassName: nginx
  rules:
    - host: a1b7563a0858f4f71b48c713a5de8c20-991979942.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /deportista
            pathType: Prefix
            backend:
              service:
                name: deportista
                port:
                  number: 80
